apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-app
  minReplicas: 2
  maxReplicas: 11
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50