apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
    spec:
      containers:
      - name: orders-app
        image: reiounagata/aaw-marketplace-bebas-orders:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "34.198.24.200"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "I5vgT5S8QFXM5z4sdN9N"
        - name: DB_NAME
          value: "orders"
        - name: AUTH_MS_URL
          value: "http://kelompok-1521852694.us-east-1.elb.amazonaws.com/auth/"
        - name: TENANT_MS_URL
          value: "http://kelompok-1521852694.us-east-1.elb.amazonaws.com/tenant/"
        - name: PORT
          value: "80"
        - name: REDIS_HOST
          value: "app-pq0e3b.serverless.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "0.25"
            memory: "384Mi"
          limits:
            cpu: "0.5"
            memory: "774Mi"