apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: reiounagata/aaw-marketplace-bebas-products:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "50.17.203.214"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "p2memMEdK1X38VtzBe9Z"
        - name: DB_NAME
          value: "products"
        - name: AUTH_MS_URL
          value: "http://k8s-bebasrouting-7cdee03608-1160077219.us-east-1.elb.amazonaws.com/"
        - name: TENANT_MS_URL
          value: "http://k8s-bebasrouting-7cdee03608-1160077219.us-east-1.elb.amazonaws.com/"
        - name: PORT
          value: "80"
        - name: REDIS_HOST
          value: "app-pq0e3b.serverless.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "0.25"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"