apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-app
  minReplicas: 1
  maxReplicas: 21
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50