apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: tenant-app
  template:
    metadata:
      labels:
        app: tenant-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tenant-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: tenant-app
        image: reiounagata/aaw-marketplace-bebas-tenant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "50.17.203.214"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "p2memMEdK1X38VtzBe9Z"
        - name: DB_NAME
          value: "tenant"
        - name: AUTH_MS_URL
          value: "http://k8s-bebasrouting-7cdee03608-915332105.us-east-1.elb.amazonaws.com"
        - name: TENANT_MS_URL
          value: "http://k8s-bebasrouting-7cdee03608-915332105.us-east-1.elb.amazonaws.com"
        - name: PORT
          value: "80"
        - name: REDIS_HOST
          value: "app-pq0e3b.serverless.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "0.125"
            memory: "128Mi"
          limits:
            cpu: "0.25"
            memory: "256Mi"