apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /tenant/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: tenant-service
            port:
              number: 8003 # Matches the 'port' in the corrected tenant-service.yaml