apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tenant-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenant-app
  minReplicas: 2
  minReplicas: 11
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50