apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - auth-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: auth-app
        image: reiounagata/aaw-marketplace-bebas-authentication:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "50.17.203.214"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "p2memMEdK1X38VtzBe9Z"
        - name: DB_NAME
          value: "authentication"
        - name: AUTH_MS_URL
          value: "http://k8s-authrouting-e2c91d2d3e-1201635246.us-east-1.elb.amazonaws.com"
        - name: TENANT_MS_URL
          value: "http://k8s-tenantrouting-e39870b395-1672028704.us-east-1.elb.amazonaws.com"
        - name: PORT
          value: "80"
        - name: REDIS_HOST
          value: "app-pq0e3b.serverless.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        - name: ADMIN_JWT_SECRET
          value: "admin_auth_ms_jwt_secret"
        - name: ADMIN_TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        resources:
          requests:
            cpu: "0.5"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10