apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Atau anotasi lain yang sesuai controller kamu
    # Jika menggunakan AWS Load Balancer Controller, anotasi mungkin berbeda
spec:
  # Pastikan ingressClassName sesuai dengan controller yang kamu gunakan (nginx atau alb)
  ingressClassName: nginx # Ganti ke 'alb' jika menggunakan AWS Load Balancer Controller
  rules:
  - http:
      paths:
      - path: /auth/
        pathType: prefix
        backend:
          service:
            name: auth-service
            port:
              number: 8000