apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-app
  template:
    metadata:
      labels:
        app: wishlist-app
    spec:
      containers:
      - name: wishlist-app
        image: reiounagata/aaw-marketplace-bebas-wishlist:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: TENANT_ID
          value: "8bd087f4-a45c-4126-b229-006dcf939625"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "database-2.cadutjy29djn.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "R7o3gHjVoGeXUQMNwbkN"
        - name: DB_NAME
          value: "wishlist"
        - name: AUTH_MS_URL
          value: "http://authentication"
        - name: TENANT_MS_URL
          value: "http://tenant"
        - name: PORT
          value: "80"
        - name: REDIS_HOST
          value: "app-pq0e3b.serverless.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "0.2"
            memory: "64Mi"
          limits:
            cpu: "0.4"
            memory: "128Mi"